---
# Installation and Configuration of the Web Server (Apache, MariaDB, PHP)
- name: Installation and Configuration of the Web Server
  hosts: all
  become: true
  connection: ssh
  gather_facts: true
